### ISSUE TITLE
Example code used in generated PHP output

### ISSUE THREAD

**Issue by AndrewCustomSumIT** [openswoole/protoc-gen-openswoole-grpc#2]
This line generates source code that contains a reference to the `HelloReply` example, set as the return type on the `_getNext` method.

https://github.com/openswoole/protoc-gen-openswoole-grpc/blob/5d71d92ceb4bd0e4b8ddd37bb74ba257dd390115/php/clienttpl.go#L69

I'm thinking it should be `{{ name $ns $m.OutputType }}`.

**Comment by andrejro2** [comment]
There are 2 issues with this method. I created a fix for that, PR is waiting for author's approval here: 
https://github.com/openswoole/protoc-gen-openswoole-grpc/pull/3

**Comment by doubaokun** [comment]
Thanks for the contribution!
